apiVersion: v1
kind: Template
metadata:
  name: "cors-proxy-deployment"
message: "Type `oc describe bc cors-proxy` to get the WebHook Payload URL"
objects:
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: cors-proxy
    labels:
      app: cors-proxy
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: cors-proxy:latest
    source:
      git:
        uri: https://github.com/3scale/cors-proxy.git
        ref: "openshift-template"
      type: Git
    strategy:
      sourceStrategy:
        forcePull: true
        from:
          kind: ImageStreamTag
          name: s2i-openresty-centos7:builder
        runtimeImage:
          kind: ImageStreamTag
          name: s2i-openresty-centos7:runtime
      type: Source
    triggers:
    - type: "GitHub"
      github:
          secret: "${GITHUB_SECRET}"

parameters:

- name: GITHUB_SECRET
  displayName: GitHub WebHook Secret
  description: Secret for Github Webhook.
  generate: expression
  from: "[a-z0-9]{12}"
  required: true
