apiVersion: v1
kind: Service
metadata:
  name: cors-proxy
  labels:
    app: cors-proxy
spec:
  ports:
    - name: http-cors-proxy
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: cors-proxy
  type: ClusterIP
  sessionAffinity: None
