apiVersion: v1
kind: Service
metadata:
  name: cors-proxy-monitoring
  labels:
    app: cors-proxy-monitoring
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9145'
spec:
  ports:
    - name: cors-proxy-monitoring
      protocol: TCP
      port: 9145
      targetPort: 9145
  selector:
    app: cors-proxy
  type: ClusterIP
  sessionAffinity: None
