apiVersion: v1
kind: Template
metadata:
  name: "cors-proxy-route"
objects:
- apiVersion: v1
  kind: Route
  metadata:
    name: cors-proxy
    labels:
      app: cors-proxy
    annotations:
      haproxy.router.openshift.io/timeout: ${TIMEOUT}s
  spec:
    host: ${HOST}
    to:
      kind: Service
      name: cors-proxy
    port:
      targetPort: http-cors-proxy
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Allow

parameters:
- name: HOST
  description: Cors Proxy Route Host
  required: true

- name: TIMEOUT
  description: Route timeout to serve requests, in seconds
  required: true
  value: "60"
