apiVersion: v1
kind: Template
metadata:
  name: "cors-proxy-secrets"
objects:
- kind: Secret
  apiVersion: v1
  stringData:
    DSN: mysql://${DB_USER}:${DB_PASSWORD}@${DB_URL}:${DB_PORT}/${DB_NAME}
    DB_USER: "${DB_USER}"
    DB_PASSWORD: "${DB_PASSWORD}"
    DB_URL: "${DB_URL}"
    DB_NAME: "${DB_NAME}"
  metadata:
    name: system-database-url 
  type: Opaque

parameters:

- name: DB_URL
  description: The cname or ip direction for the MySQL server
  required: true
- name: DB_NAME
  description: The Name of the database to be used in MySQL
  required: true
- name: DB_USER
  description: Database User
  required: true
- name: DB_PASSWORD
  description: Database Password
  required: true
- name: DB_PORT
  description: Database Port
  value: "3306"
  required: false
