apiVersion: v1
kind: Service
metadata:
  name: cors-proxy
  creationTimestamp: null
  labels:
    app: cors-proxy
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: cors-proxy
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
